name: $( BuildDefinitionName )_$(yyyyMMDD)$(rev:.r)

trigger: 
  - main 

pr: none 


variables:
 - name: repository 
   value: 'kbbrajeshazdevops'
 - name: dockerfile
   value: '$(Build.SourcesDirectory)/aspnet-core-dotnet-core/Dockerfile'
 - name: acrconnection
   value: 'acrkbbazdevops2731-acr-connection'




stages: 
 - stage: Build 
   displayName: Build and push to ACR 
   jobs: 
    - job: Build 
      displayName: Build Job 
      steps: 
       - task: Docker@2
         displayName:  Build and push an image to ACR registry
         inputs: 
          command: buildAndPush
          repository: ${{ variables. repository }}
          dockerfile: ${{ variables.dockerfile }}
          containerRegistry: ${{ variables.acr }}
          tags: $(Build.BuildId)